"""add ai_brief_json and complexity to orders

Revision ID: d641c77e25ed
Revises: c53ecbd60e3f
Create Date: 2026-06-01 01:41:14.157438
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd641c77e25ed'
down_revision: Union[str, None] = 'c53ecbd60e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ai_brief_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('complexity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'complexity')
    op.drop_column('orders', 'ai_brief_json')
    # ### end Alembic commands ###
